name: CI

on:
  push:
    branches:
      - master
env:
  REPOSITORY_PATH: https://wszgrcy:${{secrets.ACCESS_TOKEN}}@github.com/
  GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: init
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@gmail.com"
      - name: git
        run: |
          git clone ${REPOSITORY_PATH}${GITHUB_REPOSITORY}.git
          cd github-actions-test
      # - uses: actions/checkout@v2-beta
      #   with:
      #     token: ${{ secrets.ACCESS_TOKEN }}
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: build

        run: |
          pwd
          cd github-actions-test
          # git pull ${REPOSITORY_PATH}${GITHUB_REPOSITORY}.git
          # echo $GITHUB_REPOSITORY
          echo ${REPOSITORY_PATH}${GITHUB_REPOSITORY}.git
          set
          npm i
          # npm run build
          ls -l

          git config --system --list
          git config --global  --list
          git config --local  --list
          touch test123
          git add -A
          git status
          git commit -m 'test'
          ls -l

          git push "${REPOSITORY_PATH}${GITHUB_REPOSITORY}.git" master
          # git branch -d gh-pages
          # git branch gh-pages
          # git checkout gh-pages
          ls -l
          # git pull
