name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: build
        run: |
          npm i
          ls -l
          npm run build
          ls -l
          git push origin :gh-pages
          git pull


