name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: build
        env:
          TOKEN: https://${{secrets.ACCESS_TOKEN}}@github.com/${{GITHUB_REPOSITORY}}.git
        run: |
          npm i
          ls -l
          npm run build
          ls -l
          git config --global user.name "wszgrcy"
          git config --global user.email "wszgrcy@gmail.com"
          git push --force ${TOKEN} :gh-pages
          git pull


